export const REQUEST_SEARCH_ID = 'REQUEST_SEARCH_ID';
export const REQUEST_SEARCH_ID_SUCCESS = 'REQUEST_SEARCH_ID_SUCCESS';
export const REQUEST_TICKETS = 'REQUEST_TICKETS';
export const REQUEST_TICKETS_SUCCESS = 'REQUEST_TICKETS_SUCCESS';
